package com.github.apsk.jocorpora;

public final class Letter {
    public static byte encode(char letter) {
        switch (letter) {
            case 'А': return 0;
            case 'Б': return 1;
            case 'В': return 2;
            case 'Г': return 3;
            case 'Д': return 4;
            case 'Е': return 5;
            case 'Ё': return 6;
            case 'Ж': return 7;
            case 'З': return 8;
            case 'И': return 9;
            case 'Й': return 10;
            case 'К': return 11;
            case 'Л': return 12;
            case 'М': return 13;
            case 'Н': return 14;
            case 'О': return 15;
            case 'П': return 16;
            case 'Р': return 17;
            case 'С': return 18;
            case 'Т': return 19;
            case 'У': return 20;
            case 'Ф': return 21;
            case 'Х': return 22;
            case 'Ц': return 23;
            case 'Ч': return 24;
            case 'Ш': return 25;
            case 'Щ': return 26;
            case 'Ъ': return 27;
            case 'Ы': return 28;
            case 'Ь': return 29;
            case 'Э': return 30;
            case 'Ю': return 31;
            case 'Я': return 32;
            case 'а': return 33;
            case 'б': return 34;
            case 'в': return 35;
            case 'г': return 36;
            case 'д': return 37;
            case 'е': return 38;
            case 'ё': return 39;
            case 'ж': return 40;
            case 'з': return 41;
            case 'и': return 42;
            case 'й': return 43;
            case 'к': return 44;
            case 'л': return 45;
            case 'м': return 46;
            case 'н': return 47;
            case 'о': return 48;
            case 'п': return 49;
            case 'р': return 50;
            case 'с': return 51;
            case 'т': return 52;
            case 'у': return 53;
            case 'ф': return 54;
            case 'х': return 55;
            case 'ц': return 56;
            case 'ч': return 57;
            case 'ш': return 58;
            case 'щ': return 59;
            case 'ъ': return 60;
            case 'ы': return 61;
            case 'ь': return 62;
            case 'э': return 63;
            case 'ю': return 64;
            case 'я': return 65;
        }
        return -1;
    }

    public static char decode(byte code) {
        switch (code) {
            case 0: return 'А';
            case 1: return 'Б';
            case 2: return 'В';
            case 3: return 'Г';
            case 4: return 'Д';
            case 5: return 'Е';
            case 6: return 'Ё';
            case 7: return 'Ж';
            case 8: return 'З';
            case 9: return 'И';
            case 10: return 'Й';
            case 11: return 'К';
            case 12: return 'Л';
            case 13: return 'М';
            case 14: return 'Н';
            case 15: return 'О';
            case 16: return 'П';
            case 17: return 'Р';
            case 18: return 'С';
            case 19: return 'Т';
            case 20: return 'У';
            case 21: return 'Ф';
            case 22: return 'Х';
            case 23: return 'Ц';
            case 24: return 'Ч';
            case 25: return 'Ш';
            case 26: return 'Щ';
            case 27: return 'Ъ';
            case 28: return 'Ы';
            case 29: return 'Ь';
            case 30: return 'Э';
            case 31: return 'Ю';
            case 32: return 'Я';
            case 33: return 'а';
            case 34: return 'б';
            case 35: return 'в';
            case 36: return 'г';
            case 37: return 'д';
            case 38: return 'е';
            case 39: return 'ё';
            case 40: return 'ж';
            case 41: return 'з';
            case 42: return 'и';
            case 43: return 'й';
            case 44: return 'к';
            case 45: return 'л';
            case 46: return 'м';
            case 47: return 'н';
            case 48: return 'о';
            case 49: return 'п';
            case 50: return 'р';
            case 51: return 'с';
            case 52: return 'т';
            case 53: return 'у';
            case 54: return 'ф';
            case 55: return 'х';
            case 56: return 'ц';
            case 57: return 'ч';
            case 58: return 'ш';
            case 59: return 'щ';
            case 60: return 'ъ';
            case 61: return 'ы';
            case 62: return 'ь';
            case 63: return 'э';
            case 64: return 'ю';
            case 65: return 'я';
        }
        return '?';
    }
}
